name: Asobi Alerts

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v2
      - run: uv run python src/main.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          ALERT_DAYS: ${{ vars.ALERT_DAYS }}
